### ISSUE TITLE
TF-Image für Katharina

### ISSUE THREAD

**Issue by cgawron** [fhswf/Jupyterhub-K8s#17]
Folgende Pakete werden benötigt:

```
keras
keras-preprocessing
keras-tuner
matplotlib
mysql-connector-python
numpy
pandas
scikit-learn
seaborn
sqlalchemy
pymysql
tensorboard
tensorflow
```

**Comment by DeepCowProductions** [comment]
TensorRT ist nicht in der Standardinstallation von TF. Ich schätze nicht, dass wir das brauchen?

**Comment by DeepCowProductions** [comment]
TensorFlow is now part of the new deepml image for all kinds of ml and ai-development
