### ISSUE TITLE
Java Image

### ISSUE THREAD

**Issue by DeepCowProductions** [fhswf/Jupyterhub-K8s#22]
Not sure if this would be a great experience, but maybe worth a try.
Maven based Java development environment with VS Code.

**Comment by DeepCowProductions** [comment]
JetBrains is currently working on a browser based IDE. However, this would most likely be a paid service.

**Comment by cgawron** [comment]
See [fhswf/OpenLibertyTemplate](https://github.com/fhswf/OpenLibertyTemplate). This would allow JEE courses in our cluster.

**Comment by DeepCowProductions** [comment]
Looking into this: https://www.eclipse.org/che/ and then we can combine this with an JEE server.

**Comment by DeepCowProductions** [comment]
Lets try out a native maven/gradle install first. JEE server can be proxied by VS Code, which most likely will be our default IDE anyway.
