### ISSUE TITLE
Curl is needed in the NLP Image. Please install. Thanks.

### ISSUE THREAD

**Issue by botox-100** [fhswf/Jupyterhub-K8s#26]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by botox-100** [comment]
@cgawron

**Comment by cgawron** [comment]
@botox-100 Please use the **Deep Learning and Datascience** image instead of the NLP image.
This is our new "general purpose" image and includes `curl` as well.
