### ISSUE TITLE
CUDA >= 12 needed for running packages properly

### ISSUE THREAD

**Issue by vladislabv** [fhswf/Jupyterhub-K8s#38]
Feature Request:

In our current study project we work with pytorch-lightning (https://lightning.ai/docs/pytorch/stable/) to train our custom LNN model. The problem is that the package works as for 1.5 years with CUDA 12. By installing it on CUDA 11,7, we are getting unexpected error which makes enable to train our model on the GPU.

It would be great to have latest stable cuda (12.6) in the Deep Learning and Datascience spawn option.

**Comment by DeepCowProductions** [comment]
12.6 is not yet fully supported by Tf, pytroch and some other preisntalled things.
The new Version will have the CUDA 12.5.1 cudnn 9.2.1 and TensorRT 10.3.

**Comment by DeepCowProductions** [comment]
New base images are now live. The new Version for pytorch-lightning should also work now, feel free to try.
