### ISSUE TITLE
CUDA Driver is too old (11070)

### ISSUE THREAD

**Issue by cvhrnkmp** [fhswf/Jupyterhub-K8s#42]
**Describe the bug**
CUDA Driver is too old (11070)

**To Reproduce**
Use actual PyTorch Library

**Expected behavior**
Updated Cuda Driver on latest-stable version.

**Screenshots**

> RuntimeError: The NVIDIA driver on your system is too old (found version 11070). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org/ to install a PyTorch version that has been compiled with your version of the CUDA driver.

Please Update the driver, thanks in advance.

Best regards
Christian

**Comment by DeepCowProductions** [comment]
I updated some broken dependencies, torch and tf together just does not work anymore.
New image for pytroch is here: https://github.com/fhswf/Jupyterhub-K8s/pkgs/container/jupyterhub-k8s%2Fdeepml with the tag sha-16ca7d3
Also live on our Cluster.
