### ISSUE TITLE
Latex Editor

### ISSUE THREAD

**Issue by DeepCowProductions** [fhswf/Jupyterhub-K8s#8]
Create, edit and compile Latex documents in the lab.

**Additional context**
Can be done with vscode + extension, or via an overleaf installation in the container.

**Discussion Question**
Integrate Latex in all images or use a separate one?
Latex install + editor can be quite heavy. A downside of splitting would be the inability to edit code/ review written code when writing a document about such.

**Comment by hgiefers** [comment]
How about a central Overleaf deployment? One key feature of overleaf is cooperative writing ... by using a separate installation per user, this feature would not be utilized.
